export const LANDING = '/'
export const MAIN = '/main'
export const PARTY = '/party'
export const MEETS = '/meets'
export const MEET = '/meet'
export const SIGNUP = '/signup'
export const SIGNIN = '/signin'
export const RESET_PASSWORD = '/reset'
