export const LANDING = '/'
export const SIGNUP = '/signup'
export const SIGNIN = '/signin'
export const RESET_PASSWORD = '/reset'
export const MEETS = '/meets'
export const MEET = '/meets/:id'
export const APP = '/app'
export const PARTY = '/:party'
